language: android
machine:
  java:
    version: openjdk8
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
script: "./gradlew clean build"
sudo: false